package ml2changliangs
//sql类型
const(
  ChaXunBiao="ChaXunBiao"
  ChaXunZiDuans="ChaXunZiDuans"
)
//查询表
const(
  JieGou="JieGou"
  RiZhi="RiZhi"
  ZongLing="ZongLing"
)
//参数名
const(
  LeiBie="LeiBie"
)

const(
  LieBiaos="LieBiaos"
  DuiXiangs="DuiXiangs"
  LieBiaosDuiXiangs="LieBiaosDuiXiangs"
)
//字段
const(
  BianMa="BianMa"
  MingCheng="MingCheng"
  BsjBiao="BsjBiao"
  ZdsjBiao="ZdsjBiao"
  ZhengZe="ZhengZe"
  ShiJian="ShiJian"
  CanShu="CanShu"
  BiaoMing="BiaoMing"
  ZiDuan="ZiDuan"
  BiaoJiShu="BiaoJiShu"
  ZiDuanJiShu="ZiDuanJiShu"
)