package ml2changliangs

//参数
const(
BiaoMing="BiaoMing"
ZiDuanMing="ZiDuanMing"
)

//业务表名
const(
Ywb1YongHus="Ywb1YongHus"
)

//基础表名
const(
Bm1BiaoMings="Bm1BiaoMings"
Bm2ZiDuans="Bm2ZiDuans"
Bm3YeWus="Bm3YeWus"
Bm4FangFas="Bm4FangFas"
Bm5ZiDuanXingWeiLius="Bm5ZiDuanXingWeiLius"
Bm6ZiDuanZhiDings="Bm6ZiDuanZhiDings"
Bm7RuCans="Bm7RuCans"
Bm8ChuCans="Bm8ChuCans"
)
//sql常用
const(
VARCHAR="VARCHAR"
BIGINT="BIGINT"
INT="INT"
)
//字段名
const(
BiXu="BiXu"
FuBianMa="FuBianMa"
YeWuZhuJian="YeWuZhuJian"
FangFaGeShu="FangFaGeShu"
ShunXu="ShunXu"
FangFaMing="FangFaMing"
MiaoShu="MiaoShu"
ZiDuanZhuJian="ZiDuanZhuJian"
KeNengZhi="KeNengZhi"
KeNengZhiMiaoShu="KeNengZhiMiaoShu"
ZhengZe="ZhengZe"
ShiFouZhiDing="ShiFouZhiDing"
ShiFouYouXingWei="ShiFouYouXingWei"
ZhuJian="ZhuJian"
MingCheng="MingCheng"
BianMa="BianMa"
ZhuJianBiao="ZhuJianBiao"
ZhiBiao="ZhiBiao"
ZjBiao="ZjBiao"
ZdBiao="ZdBiao"
ZiDuans="ZiDuans"
LeiXing="LeiXing"
ChangDu="ChangDu"
MoRenZhi="MoRenZhi"
)