package ml2changliangs
//表名
const(
  
)
//sql常用
const(
VARCHAR="VARCHAR"
BIGINT="BIGINT"
INT="INT"
)
//字段名
const(
ZiDuan="ZiDuan"
ZhengZe="ZhengZe"
ShiFouZhiDing="ShiFouZhiDing"
ShiFouYouXingWei="ShiFouYouXingWei"
ZhuJian="ZhuJian"
MingCheng="MingCheng"
BianMa="BianMa"
ZhuJianBiao="ZhuJianBiao"
ZhiBiao="ZhiBiao"
ZjBiao="ZjBiao"
ZdBiao="ZdBiao"
ZiDuans="ZiDuans"
BiaoMing="BiaoMing"
LeiXing="LeiXing"
ChangDu="ChangDu"
MoRenZhi="MoRenZhi"
)